apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-backend-deployment
  labels:
    app: golang-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-backend
  template:
    metadata:
      labels:
        app: golang-backend
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

